### ISSUE TITLE
Error in post_gen_project script

### ISSUE THREAD

**Issue by pemeunier** [HelmholtzAI-Consultants-Munich/Quicksetup-ai#25]
I get this error while trying to execute cookiecutter.

```
Traceback (most recent call last):
  File "C:\Users\aaa\AppData\Local\Temp\tmpg8lvl1vc.py", line 28, in <module>
    delete_license_dir()
  File "C:\Users\aaa\AppData\Local\Temp\tmpg8lvl1vc.py", line 24, in delete_license_dir
    subprocess.run(["rm", "-r", "licenses/"])
  File "C:\Users\aaa\AppData\Local\mambaforge\envs\venv_cookie\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\aaa\AppData\Local\mambaforge\envs\venv_cookie\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\aaa\AppData\Local\mambaforge\envs\venv_cookie\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable
ERROR: Stopping generation because post_gen_project hook script didn't exit successfully
Hook script failed (exit status: 1)
```

**Comment by IsraMekki0** [comment]
Hello!
Looks like you're trying to run on Windows. And we haven't thoroughly tested the pipeline there..
This error should be fixed now.
Please let us know if you run into some other problems!
